### ISSUE TITLE
Hello Can I know the type of data you have trained on?

### ISSUE THREAD

**Issue by mohammed-Emad** [rabi3elbeji/text-recognitionRCNN#1]
Hello Can I know the type of data you have trained on?
I mean to build:
frozen_inference_graph.pb؟
Thanks

**Comment by rabi3elbeji** [comment]
Hello,
I used images of  [ICDAR 2015 competition](http://rrc.cvc.uab.es/?ch=4&com=downloads) 
**Text Localization Task**

**Comment by mohammed-Emad** [comment]
Thank you very much for your response
If possible, some guidance on training methods

**Comment by rabi3elbeji** [comment]
You are welcome 😃 

The training is based on the [Tensorflow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection).

I add the different steps I took to adapt the training to the text in this [notebook file](https://github.com/rabi3elbeji/text-recognitionRCNN/blob/master/text_detection_training.ipynb)

**Comment by mohammed-Emad** [comment]
thank you very much ,

**Comment by mohammed-Emad** [comment]
Hello
I apologize for the inconvenience
But the location
http://rrc.cvc.uab.es/?ch=4&com=downloads
Stopped
Is there no alternative?

**Comment by rabi3elbeji** [comment]
Hi,
Check [this link](http://dagdata.cvc.uab.es/icdar2013competition/?ch=1&com=tasks) -- **Text Localization Task**
There are several versions of the ICDAR dataset online (2003 ... 2017). Just check one of those challenges and download the right dataset of images with the ground-truth.
You must also register as a member to download!
